### ISSUE TITLE
broken "donate" link

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/opencv.org#40] opened 2019-05-22 16:47 UTC
from: https://answers.opencv.org/question/213315/paypal-always-gives-an-error/

"Donate" button on the main opencv.org page leads to an expired session

**Comment by mshabunin** [comment] 2019-05-22 16:55
**cc** @spmallick

**Comment by mshabunin** [comment] 2019-05-27 09:25
While the issue is being fixed you can use "Donate" button on old page (https://opencv-infrastructure.github.io/opencv.org/)

**Comment by spmallick** [comment] 2019-05-27 12:54
Looks like this message got filtered in my account. This is now fixed. Thanks for bringing this to our attention.

**Closed as completed** 2019-05-27 13:11 UTC
